AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: An AWS Serverless Specification template describing your function.
Resources:
  alemoinetest:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./lambda_function
      Description: ''
      MemorySize: 128
      Timeout: 60
      Layers:
        - !Ref TempConversionDepLayer

  TempConversionDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: pyodbc
      Description: dependency layer
      ContentUri: layers/pyodbc
      CompatibleRuntimes:
        - python3.7
        - python3.6